### ISSUE TITLE
Feature for adding extra templated output to the diff

### ISSUE THREAD

**Issue by simonw** [simonw/csv-diff#38]
For this project: https://github.com/simonw/scrape-hacker-news-by-domain

I want to include `latest` links in the human readable output that link to https://news.ycombinator.com/latest?id=41459472 for each item.

I'm going to try using Python format strings like this:

```bash
csv-diff --format json simon-previous.json simon.json --key id --extra latest 'https://news.ycombinator.com/latest?id={id}'
```

**Comment by simonw** [comment]
Got that working:
```
3 rows changed

  id: 41459472
    points: "24" => "25"
    numComments: "5" => "6"
  extras:
    latest: https://news.ycombinator.com/latest?id=41459472

  id: 41434857
    points: "1" => "2"
  extras:
    latest: https://news.ycombinator.com/latest?id=41434857

  id: 41427834
    points: "2" => "3"
  extras:
    latest: https://news.ycombinator.com/latest?id=41427834
```
